import { Property, FeaturedProperty, Category } from './types';

export const PROPERTIES: Property[] = [
    {
        id: 1,
        x: 22,
        y: 38,
        price: '$485K',
        beds: 3,
        baths: 2,
        area: 124,
        type: 'Квартира',
        title: 'Sky Loft на Печерську',
        district: 'Печерськ, Київ',
        status: 'sale',
    },
    {
        id: 2,
        x: 38,
        y: 52,
        price: '$1.2M',
        beds: 5,
        baths: 4,
        area: 280,
        type: 'Будинок',
        title: 'Вілла з видом на Дніпро',
        district: 'Конча-Заспа',
        status: 'sale',
    },
    {
        id: 3,
        x: 56,
        y: 30,
        price: '$2.4K',
        beds: 2,
        baths: 1,
        area: 68,
        type: 'Квартира',
        title: 'Студія в історичному домі',
        district: 'Поділ, Київ',
        status: 'rent',
    },
    {
        id: 4,
        x: 70,
        y: 58,
        price: '$680K',
        beds: 4,
        baths: 3,
        area: 186,
        type: 'Таунхаус',
        title: 'Сучасний таунхаус',
        district: 'Софіївська Борщагівка',
        status: 'sale',
    },
    {
        id: 5,
        x: 46,
        y: 72,
        price: '$3.8K',
        beds: 3,
        baths: 2,
        area: 95,
        type: 'Пентхаус',
        title: 'Пентхаус з терасою',
        district: 'Шевченківський',
        status: 'rent',
    },
    {
        id: 6,
        x: 82,
        y: 40,
        price: '$320K',
        beds: 2,
        baths: 1,
        area: 72,
        type: 'Квартира',
        title: 'Light Apartment 72',
        district: 'Оболонь',
        status: 'sale',
    },
    {
        id: 7,
        x: 30,
        y: 18,
        price: '$5.6K',
        beds: 4,
        baths: 3,
        area: 210,
        type: 'Будинок',
        title: 'Family House',
        district: 'Козин',
        status: 'rent',
    },
    {
        id: 8,
        x: 64,
        y: 80,
        price: '$890K',
        beds: 4,
        baths: 3,
        area: 175,
        type: 'Квартира',
        title: 'Glass Tower Residence',
        district: 'Голосіївський',
        status: 'sale',
    },
];

export const FEATURED: FeaturedProperty[] = [
    {
        id: 'a',
        title: 'Skyline Loft 42',
        price: '$485,000',
        spec: '3 кімн · 124 м² · Печерськ',
        tag: 'Новинка',
        color: '248 84 64',
    },
    {
        id: 'b',
        title: 'Riverside Villa',
        price: '$1,200,000',
        spec: '5 кімн · 280 м² · Конча-Заспа',
        tag: 'Преміум',
        color: '32 90 58',
    },
    {
        id: 'c',
        title: 'Old Town Studio',
        price: '$2,400 / міс',
        spec: '2 кімн · 68 м² · Поділ',
        tag: 'Оренда',
        color: '210 60 50',
    },
    {
        id: 'd',
        title: 'Glass Penthouse',
        price: '$3,800 / міс',
        spec: '3 кімн · 95 м² · Центр',
        tag: 'Топ-вибір',
        color: '16 86 60',
    },
];

export const CATEGORIES: Category[] = [
    { key: 'buy', label: 'Купити', count: '12 480', icon: 'key' },
    { key: 'rent', label: 'Орендувати', count: '6 320', icon: 'bed' },
    { key: 'comm', label: 'Комерційна', count: '1 845', icon: 'office' },
    { key: 'new', label: 'Новобудови', count: '412', icon: 'crane' },
];
